/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DiscordIcon: typeof import('../src/components/icons')['DiscordIcon']
  const GithubIcon: typeof import('../src/components/icons')['GithubIcon']
  const HeartFilledIcon: typeof import('../src/components/icons')['HeartFilledIcon']
  const HomeFloatProjectsUnline: typeof import('../src/ui/home-float-projects-unline')['HomeFloatProjectsUnline']
  const Icon: typeof import('@iconify/react')['Icon']
  const Logo: typeof import('../src/components/icons')['Logo']
  const MoonFilledIcon: typeof import('../src/components/icons')['MoonFilledIcon']
  const Mouse: typeof import('../src/components/mouse')['Mouse']
  const Navbar: typeof import('../src/layouts/components/navbar')['Navbar']
  const SearchIcon: typeof import('../src/components/icons')['SearchIcon']
  const SunFilledIcon: typeof import('../src/components/icons')['SunFilledIcon']
  const ThemeSwitch: typeof import('../src/layouts/components/theme-switch')['ThemeSwitch']
  const TwitterIcon: typeof import('../src/components/icons')['TwitterIcon']
  const clsx: typeof import('clsx')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const layouts: typeof import('../src/layouts/index')['layouts']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const startTransition: typeof import('react')['startTransition']
  const subtitle: typeof import('../src/components/primitives')['subtitle']
  const title: typeof import('../src/components/primitives')['title']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
