/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AppleDownloadIcon: typeof import('../src/components/icons')['AppleDownloadIcon']
  const AppleIcon: typeof import('../src/components/icons')['AppleIcon']
  const BinanceIcon: typeof import('../src/components/icons')['BinanceIcon']
  const CloseIcon: typeof import('../src/components/icons')['CloseIcon']
  const CustodyIcon: typeof import('../src/components/icons')['CustodyIcon']
  const DeFiIcon: typeof import('../src/components/icons')['DeFiIcon']
  const DiscordIcon: typeof import('../src/components/icons')['DiscordIcon']
  const DividerVerticalCubes: typeof import('../src/components/divider-vertical-cubes')['DividerVerticalCubes']
  const DividerVerticalCubesThree: typeof import('../src/components/divider-vertical-cubes-three')['DividerVerticalCubesThree']
  const GateIcon: typeof import('../src/components/icons')['GateIcon']
  const GithubIcon: typeof import('../src/components/icons')['GithubIcon']
  const GoogleDownloadIcon: typeof import('../src/components/icons')['GoogleDownloadIcon']
  const GooglePlayDownloadIcon: typeof import('../src/components/icons')['GooglePlayDownloadIcon']
  const HeartFilledIcon: typeof import('../src/components/icons')['HeartFilledIcon']
  const HomeEcosystemNarquee: typeof import('../src/ui/home-ecosystem-narquee')['HomeEcosystemNarquee']
  const HomeFloatProjectsUnline: typeof import('../src/ui/home-float-projects-unline')['HomeFloatProjectsUnline']
  const Icon: typeof import('@iconify/react')['Icon']
  const JdiIcon: typeof import('../src/components/icons')['JdiIcon']
  const KucionIcon: typeof import('../src/components/icons')['KucionIcon']
  const Logo: typeof import('../src/components/icons')['Logo']
  const MediumIcon: typeof import('../src/components/icons')['MediumIcon']
  const MenuIcon: typeof import('../src/components/icons')['MenuIcon']
  const MoonFilledIcon: typeof import('../src/components/icons')['MoonFilledIcon']
  const Mouse: typeof import('../src/components/mouse')['Mouse']
  const Navbar: typeof import('../src/layouts/components/navbar')['Navbar']
  const OkxIcon: typeof import('../src/components/icons')['OkxIcon']
  const PrivacyIcon: typeof import('../src/components/icons')['PrivacyIcon']
  const SearchIcon: typeof import('../src/components/icons')['SearchIcon']
  const SunFilledIcon: typeof import('../src/components/icons')['SunFilledIcon']
  const SwapsIcon: typeof import('../src/components/icons')['SwapsIcon']
  const TelegramIcon: typeof import('../src/components/icons')['TelegramIcon']
  const ThemeSwitch: typeof import('../src/layouts/components/theme-switch')['ThemeSwitch']
  const TwitterIcon: typeof import('../src/components/icons')['TwitterIcon']
  const UobIcon: typeof import('../src/components/icons')['UobIcon']
  const YoutubeIcon: typeof import('../src/components/icons')['YoutubeIcon']
  const ZhongXingIcon: typeof import('../src/components/icons')['ZhongXingIcon']
  const clsx: typeof import('clsx')['default']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const layouts: typeof import('../src/layouts/index')['layouts']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const motion: typeof import('framer-motion')['motion']
  const startTransition: typeof import('react')['startTransition']
  const store: typeof import('../src/store/index')['default']
  const subtitle: typeof import('../src/components/primitives')['subtitle']
  const title: typeof import('../src/components/primitives')['title']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouter: typeof import('next/router')['useRouter']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { IconProps } from '../src/components/icons'
  import('../src/components/icons')
}
